### ISSUE TITLE
Editing Search box location + changing hotkeys

### ISSUE THREAD

**Issue by shanerodrigues** [khanhas/ueli#2]
I was wondering am I able to adjust where the search box is actually placed? Also I'm trying to change a hotkey placement, the "shift+space" one. I changed it to "shift+space+f" and reloaded ueli but it still registers the "shift+space" hotkey and ignores my new hotkey.

**Comment by shmykelsa** [comment]
I've got the same hotkeys issue

**Comment by khanhas** [comment]
1. Where else you would like to place it?
2. You need to restart ueli.

**Comment by shanerodrigues** [comment]
1. Ideally I would like it to be placed in the middle of the screen and 30 or so pixels downwards from its current location.
2. Yes, I've tried doing that to no avail. I've also tried re-installing ueli and changing the hotkey, reloading it again and there's no difference.

**Comment by shanerodrigues** [comment]
hey @khanhas have you been able to look into this? Can you point out how I could change the location of it?

**Comment by khanhas** [comment]
Sorry. I barely have free time this week. I will take a look next weekend.

**Comment by khanhas** [comment]
Try v4.6.2 @theSR18

**Comment by shanerodrigues** [comment]
> 
> 
> Try v4.6.2 @theSR18

Thanks for updating it but I seem to have an issue with implementing it. Has the command been added to the config.json file or do I have to add it myself? If so on the config.json file where exactly do I put it? and how do I make sure that the updated config reflects on the app?

Also, I've tried altering the shift+space hotkey for "hotkeyRunModeCwd" yet it still responds to shift+space, any idea on how to solve that? 

Sorry for all the questions but if these two were solved the launcher would be perfect.

**Comment by khanhas** [comment]
1. It's an optional config so you need to add it yourself.
![b](https://user-images.githubusercontent.com/26436809/56092344-658db280-5efe-11e9-9ac6-9aa6eb9ccde5.png)

2. If it doesn't change corresponding to your config, it means ueli is using default config. I have no idea how it is possible for ueli to behave that way. I checked everything.

**Comment by shanerodrigues** [comment]
Yeah it's actually pretty strange, no matter what I change the values to it just doesn't update. I've saved the config, closed ueli opened it up again from the folder that I extracted it to yet it stays the same. Well, thanks for trying to solve it though.

**Comment by shmykelsa** [comment]
I can confirm what @theSR18 said. No matter how many times I've tried to change the values, let Ueli re-make a config, it always fails at applying changes.

**Comment by DELUUXE** [comment]
It seems to apply the config when starting ueli as administrator.

**Comment by shanerodrigues** [comment]
Thanks @DELUUXE, starting ueli as administrator did in fact work!
