### ISSUE TITLE
Changing Web Search Engine prefix has no effect

### ISSUE THREAD

**Issue by shmykelsa** [khanhas/ueli#3]
Even if I cange the prefix to search for a search engine, the setting will never apply and it's always the same.

**Comment by khanhas** [comment]
If it doesn't change, it means there is problem with your config file and ueli will use default config.
1. Delete current config file
2. Restart ueli to generate the valid one.
3. Read https://github.com/khanhas/ueli#customization carefully to determine what type of field you want to change is.

**Comment by shmykelsa** [comment]
Hey @khanhas 

Thanks for the reply, but I've done it several times, but still no effect. Youtube will always be triggered with "yt" even though I've set it with "y". Same applies for Google Images.
