### ISSUE TITLE
What cursor are you using?

### ISSUE THREAD

**Issue by Niroa95** [khanhas/ueli#8]
I know this issue isn't related to this project, but I needed to ask. That cursor you're using in the screenshots of [this project](https://github.com/khanhas/spicetify) is really beautiful. So I wanted to ask if you could tell me what theme it is. It looks like oxygen cursors but those are more rounded.

**Comment by khanhas** [comment]
Sorry, I forgot its name. I saved them on my drive before but I lost them now.
