### ISSUE TITLE
Bugs bugs bugs!

### ISSUE THREAD

**Issue by dudeisbrendan03** [khanhas/ueli#9]
Are you planning on coming back to this or is it a lost cause? [oliverschwendener/ueli](https://github.com/oliverschwendener/ueli) has gone a long way with new features and fixes, are you planning to catch up?

**Comment by khanhas** [comment]
Sorry, haha.
I'm no longer use Windows anymore so probably never

**Comment by dudeisbrendan03** [comment]
Aw, that's sad to hear. Can you guide me through how you themed it? ueli now supports some custom css, but I'm not sure if that's enough to get it where yours is.

**Comment by khanhas** [comment]
Find file `%userprofile%\ueli.custom.css`
